from .views import *
from django.urls import path, include

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='author-list'),
    path('authors/<int:pk>/', AuthorDetailedView.as_view(), name='author-detailed'),
    path('books/', IndexView.as_view(), name='books'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('books/<int:pk>/edit/', edit_book, name='book-edit'),
    path('books/create/', create_book, name='book-create'),
    path('books/<int:pk>/delete/', delete_book, name='book-delete'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('countries/<int:pk>/', CountryDetailedView.as_view(), name='country-detailed'),
    path('genres/', GenreListView.as_view(), name='genre-list'),
    path('genres/<int:pk>/', GenreDetailedView.as_view(), name='genre-detailed'),
    path('loans/', LoanListView.as_view(), name='loan-list'),
    path('loans/<int:pk>/', LoanDetailedView.as_view(), name='loan-detailed'),
    path('publishers/', PublisherListView.as_view(), name='publisher-list'),
    path('publishers/<int:pk>/', PublisherDetailedView.as_view(), name='publisher-detailed'),
    path('readers/', ReaderListView.as_view(), name='reader-list'),
    path('readers/<int:pk>/', ReaderDetailedView.as_view(), name='reader-detailed'),
    path('reviews/', ReviewListView.as_view(), name='review-list'),
    path('reviews/<int:pk>/', ReviewDetailedView.as_view(), name='review-detailed'),
    path('report/', ReportView.as_view(), name='report'),
    path('courses/', course_list, name='course-list'),
    path('courses/<int:course_id>/', course_detail, name='course-detail'),
    path('courses/<int:course_id>/delete/', course_delete, name='course-delete'),
    path('books-by-genre/', books_by_genre, name='books-by-genre'),
    path('average-author-rating/', avg_author_rating, name='average-author-rating'),
    path('authors-by-country/', authors_by_country, name='authors-by-country'),
    path('loans-by-reader/', loan_count_by_reader, name='loan-count-by-reader'),
    path('loans-per-month/', loans_per_month, name='loans-per-month'),
    path('top-authors/', top_authors_by_books, name='top-authors-by-books'),
    path('dashboard/v1/', Dashboardv1.as_view(),name='dashboard-v1')
]